[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18", NEXT_PRIVATE_TARGET = "server" }

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
